1.9/Dockerfile, 1.9/wheezy/Dockerfile, 2.0/Dockerfile, 2.0/wheezy/Dockerfile, 2.1/Dockerfile, 2.1/wheezy/Dockerfile, 2.2/Dockerfile, 2.2/wheezy/Dockerfile
Fixes #31. Running a build test...
=> Fix gdbm not being available, remove deps that are now in buildpack-deps

2.0/Dockerfile, 2.0/slim/Dockerfile, 2.1/Dockerfile, 2.1/slim/Dockerfile, 2.2/Dockerfile, 2.2/slim/Dockerfile, update.sh
Closes #47, but I need to rebase it into a single commit before it can be merged.
To reiterate the issue, the idea is to explicitly manage rubygems versions, just as is done with bundler.
=> update rubygems to 2.4.8

2.0/slim/Dockerfile, 2.1/slim/Dockerfile, 2.2/slim/Dockerfile
The ruby checksum ought to be checked in the slim versions as well
=> Verify ruby checksum in slim versions

2.0/Dockerfile, 2.0/slim/Dockerfile, 2.1/Dockerfile, 2.1/alpine/Dockerfile, 2.1/slim/Dockerfile, 2.2/Dockerfile, 2.2/alpine/Dockerfile, 2.2/slim/Dockerfile, 2.3/Dockerfile, 2.3/alpine/Dockerfile, 2.3/slim/Dockerfile, Dockerfile-alpine.template, Dockerfile-slim.template, Dockerfile.template
=> Adjust the order we do things a bit to enable non-root usage trivially

2.0/Dockerfile, 2.0/slim/Dockerfile, 2.1/Dockerfile, 2.1/alpine/Dockerfile, 2.1/slim/Dockerfile, 2.2/Dockerfile, 2.2/alpine/Dockerfile, 2.2/slim/Dockerfile, 2.3/Dockerfile, 2.3/alpine/Dockerfile, 2.3/slim/Dockerfile, Dockerfile-alpine.template, Dockerfile-slim.template, Dockerfile.template
I'm a little :sheep:ish...  This was writing to `/root/.bundle/config`, and using environment variables before they existed.  Since Bundler supports environment variables for _all_ settings, let's use those instead so that this _actually_ works properly. :+1:
Fixes the shortcoming of #68 (for backlink references).
=> Fix non-root support

2.1/Dockerfile, 2.1/alpine/Dockerfile, 2.1/slim/Dockerfile, 2.2/Dockerfile, 2.2/alpine/Dockerfile, 2.2/slim/Dockerfile, 2.3/Dockerfile, 2.3/alpine/Dockerfile, 2.3/slim/Dockerfile, Dockerfile-alpine.template, Dockerfile-slim.template, Dockerfile.template
This PR adds `libruby.so` to the Ruby 2.1, 2.2, and 2.3 images by passing the `--enable-shared` flag to the `./configure` call.
I ran into issues when trying to run a Ruby app with a native library that had to be linked against `libruby.so` in Docker. Since the Ruby base image don't have it, I got `libruby.so.2.3: cannot open shared object file: No such file or directory`. This seems like a use-case that should probably be supported by the Ruby Docker images. Thus this PR.
It seems to add a few megabytes to the image size (3.6, 3.4, 2.5 MB for Ruby 2.1, 2.2, and 2.3, respectively), but AFAICT it shouldn't have any adverse consequences otherwise.
=> Build dynamic library (libruby.so)

.travis.yml, 2.1/Dockerfile, 2.1/alpine/Dockerfile, 2.1/slim/Dockerfile, 2.2/Dockerfile, 2.2/alpine/Dockerfile, 2.2/slim/Dockerfile, 2.3/Dockerfile, 2.3/slim/Dockerfile, 2.4-rc/Dockerfile, 2.4-rc/alpine/Dockerfile, 2.4-rc/onbuild/Dockerfile, 2.4-rc/slim/Dockerfile, Dockerfile-alpine.template, Dockerfile-slim.template, Dockerfile.template, update.sh
=> Add 2.4-rc builds

generate-stackbrew-library.sh
Since Ruby 2.4 is the latest release, it should be considered the default ‘2’ version.
=> 2.4 is latest

2.1/Dockerfile, 2.1/alpine/Dockerfile, 2.1/slim/Dockerfile, 2.2/Dockerfile, 2.2/alpine/Dockerfile, 2.2/slim/Dockerfile, 2.3/Dockerfile, 2.3/alpine/Dockerfile, 2.3/slim/Dockerfile, 2.4/Dockerfile, 2.4/alpine/Dockerfile, 2.4/slim/Dockerfile, Dockerfile-alpine.template, Dockerfile-slim.template, Dockerfile.template, update.sh
All the recent versions have xz tarball, which is about 40% small than gz!
=> Download smaller ruby tarball xz instead of gz

2.1/Dockerfile, 2.1/alpine/Dockerfile, 2.1/slim/Dockerfile, 2.2/Dockerfile, 2.2/alpine/Dockerfile, 2.2/slim/Dockerfile, 2.3/Dockerfile, 2.3/alpine/Dockerfile, 2.3/slim/Dockerfile, 2.4/Dockerfile, 2.4/alpine/Dockerfile, 2.4/slim/Dockerfile, Dockerfile-alpine.template, Dockerfile-slim.template, Dockerfile.template
This is along the same lines as:
- https://github.com/docker-library/tomcat/pull/70
- https://github.com/docker-library/memcached/pull/13
- https://github.com/tianon/docker-bash/pull/3
=> Add explicit "--build" to our "./configure" invocations

.travis.yml, 2.2/jessie/slim/Dockerfile, 2.3/jessie/slim/Dockerfile, 2.4/jessie/slim/Dockerfile, 2.4/stretch/Dockerfile, 2.4/stretch/onbuild/Dockerfile, 2.4/stretch/slim/Dockerfile, Dockerfile-slim.template
=> Add "stretch" variants of 2.4

2.2/alpine3.4/Dockerfile, 2.3/alpine3.4/Dockerfile, 2.4/alpine3.4/Dockerfile, 2.4/alpine3.6/Dockerfile, Dockerfile-alpine.template
This saves ~11MB of final image size (~79.4MB down to ~68.5MB).
Fixes #131
=> Adjust scanelf to properly remove "ruby-libs" in the "2.4-alpine3.6" image

.travis.yml, 2.2/alpine3.4/Dockerfile, 2.2/jessie/Dockerfile, 2.2/jessie/slim/Dockerfile, 2.3/alpine3.4/Dockerfile, 2.3/jessie/Dockerfile, 2.3/jessie/slim/Dockerfile, 2.4/alpine3.6/Dockerfile, 2.4/jessie/Dockerfile, 2.4/jessie/slim/Dockerfile, 2.4/stretch/Dockerfile, 2.4/stretch/slim/Dockerfile, 2.5-rc/alpine3.6/Dockerfile, 2.5-rc/stretch/Dockerfile, 2.5-rc/stretch/slim/Dockerfile, Dockerfile-alpine.template, Dockerfile-debian.template, Dockerfile-slim.template
Please merge https://github.com/docker-library/official-images/pull/3606 first 🙏 
Current test suite is failed because of removing mathn.rb from stdlib since Ruby 2.5
-------------------
Ruby 2.5.0-preview1 is released.
https://www.ruby-lang.org/en/news/2017/10/10/ruby-2-5-0-preview1-released/
I ran following commands to create them:
```
cp -r 2.4 2.5-rc
./update.sh
```
=> Add 2.5-rc builds

2.3/alpine3.7/Dockerfile, 2.3/jessie/Dockerfile, 2.3/jessie/slim/Dockerfile, 2.3/stretch/Dockerfile, 2.3/stretch/slim/Dockerfile, 2.4/alpine3.6/Dockerfile, 2.4/alpine3.7/Dockerfile, 2.4/jessie/Dockerfile, 2.4/jessie/slim/Dockerfile, 2.4/stretch/Dockerfile, 2.4/stretch/slim/Dockerfile, 2.5/alpine3.7/Dockerfile, 2.5/stretch/Dockerfile, 2.5/stretch/slim/Dockerfile, 2.6-rc/alpine3.7/Dockerfile, 2.6-rc/stretch/Dockerfile, 2.6-rc/stretch/slim/Dockerfile, Dockerfile-alpine.template, Dockerfile-debian.template, Dockerfile-slim.template
See https://github.com/docker-library/ruby/pull/208#issuecomment-390755292
This is a follow-up to #208.
Refs #188, #191, #193
=> Remove BUNDLE_BIN and add GEM_HOME/bin back to PATH

2.3/alpine3.7/Dockerfile, 2.4/alpine3.6/Dockerfile, 2.4/alpine3.7/Dockerfile, 2.5/alpine3.7/Dockerfile, 2.6-rc/alpine3.7/Dockerfile, Dockerfile-alpine.template
It seems it isn't runtime dependency because openssl works well without it.
```
$ docker run --rm -it ruby:alpine sh
/ # apk del libressl-dev
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
World updated, but the following packages are not removed due to:
libressl-dev: .ruby-rundeps
OK: 30 MiB in 31 packages
/ # ruby -r openssl -e 'p OpenSSL::Digest.new("sha256").hexdigest'
"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
```
This PR reduces 15.5MB of the image.
```
$ docker image ls ruby:alpine
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ruby                alpine              e8e61f5c55cb        4 days ago          62MB
$ …
```
=> Remove libressl-dev from runtime dependency

.travis.yml, 2.3/alpine3.8/Dockerfile, 2.6-rc/alpine3.8/Dockerfile, generate-stackbrew-library.sh, update.sh
Alpine 3.8 for 2.4 and 2.5 need to wait for https://bugs.ruby-lang.org/issues/14754 backports to be released (should be 2.4.5+ and 2.5.2+ respectively).
This is a partial solution to #228 (not going to close that until we get 2.4 and 2.5).
=> Add 2.3/alpine3.8 and 2.6-rc/alpine3.8

2.3/alpine3.7/Dockerfile, 2.3/alpine3.8/Dockerfile, 2.4/alpine3.6/Dockerfile, 2.4/alpine3.7/Dockerfile, 2.5/alpine3.7/Dockerfile, 2.6-rc/alpine3.7/Dockerfile, 2.6-rc/alpine3.8/Dockerfile, Dockerfile-alpine.template
This patch was OK'd by a Ruby maintainer (https://bugs.ruby-lang.org/issues/14387#note-16), but hasn't been merged because it isn't generic enough to support glibc properly, which doesn't matter here (since we're Alpine-only in this context).
Closes #196
@ncopa do you see any issue with us applying this patch to all four currently supported versions (2.3, 2.4, 2.5, 2.6-rc)?  The patch applies cleanly, so I was planning to just go for it assuming our basic "does Ruby appear to work properly?" smoke tests pass, but I'd appreciate your thoughts on whether that's safe to do
=> Apply Alpine thread stack size patch

2.3/alpine3.7/Dockerfile, 2.3/alpine3.8/Dockerfile, 2.3/jessie/Dockerfile, 2.3/jessie/slim/Dockerfile, 2.3/stretch/Dockerfile, 2.3/stretch/slim/Dockerfile, 2.4/alpine3.7/Dockerfile, 2.4/alpine3.8/Dockerfile, 2.4/jessie/Dockerfile, 2.4/jessie/slim/Dockerfile, 2.4/stretch/Dockerfile, 2.4/stretch/slim/Dockerfile, 2.5/alpine3.7/Dockerfile, 2.5/alpine3.8/Dockerfile, 2.5/stretch/Dockerfile, 2.5/stretch/slim/Dockerfile, 2.6/alpine3.7/Dockerfile, 2.6/alpine3.8/Dockerfile, 2.6/stretch/Dockerfile, 2.6/stretch/slim/Dockerfile, Dockerfile-alpine.template, Dockerfile-debian.template, Dockerfile-slim.template, update.sh
This also adjusts Bundler to be explicitly fixed at either 1.17.2 or the Ruby/Rubygems-bundled version, whichever is newer -- this is slightly older than what we've already pushed (1.17.3), but nothing in the changelog appears to be relevant, so this seems fine: https://github.com/bundler/bundler/compare/v1.17.2...v1.17.3#diff-4ac32a78649ca5bdd8e0ba38b7006a1e
For Ruby 2.6, this means we no longer do anything to the bundled Rubygems (or Bundler), and simply provide whatever comes with the Ruby release as-is, and it is now up to users to explicitly update if they need a newer version than is provided here.
Closes #246
(Eventually, this means we'll be removing *all* our `RUBYGEMS_VERSION` code too hopefully. :+1:)
=> Adjust RUBYGEMS_VERSION to be fixed at either 3.0.1 or the Ruby-bundled version, whichever is newer

2.3/jessie/slim/Dockerfile, 2.3/stretch/slim/Dockerfile, 2.4/jessie/slim/Dockerfile, 2.4/stretch/slim/Dockerfile, 2.5/stretch/slim/Dockerfile, 2.6/stretch/slim/Dockerfile, update.sh
This saves ~50MB in my testing (2.6 went from ~175MB down to ~125MB and 2.3 went from ~250MB down to ~200MB).
Closes #256
=> Adjust "slim" variants to use "slim" Debian bases

2.3/alpine3.7/Dockerfile, 2.3/alpine3.8/Dockerfile, 2.3/jessie/slim/Dockerfile, 2.3/stretch/slim/Dockerfile, 2.4/alpine3.8/Dockerfile, 2.4/alpine3.9/Dockerfile, 2.4/jessie/slim/Dockerfile, 2.4/stretch/slim/Dockerfile, 2.5/alpine3.8/Dockerfile, 2.5/alpine3.9/Dockerfile, 2.5/stretch/slim/Dockerfile, 2.6/alpine3.8/Dockerfile, 2.6/alpine3.9/Dockerfile, 2.6/stretch/slim/Dockerfile, Dockerfile-alpine.template, Dockerfile-slim.template
Closes #267 (follow-up to #266)
It turns out that if Ruby is compiled with `libgmp` available, it needs to be available for linking when building native extensions too.
=> Add "libgmp-dev" and "gmp-dev" persistently

2.3/alpine3.7/Dockerfile, 2.3/alpine3.8/Dockerfile, 2.3/jessie/Dockerfile, 2.3/jessie/slim/Dockerfile, 2.3/stretch/Dockerfile, 2.3/stretch/slim/Dockerfile, 2.4/alpine3.8/Dockerfile, 2.4/alpine3.9/Dockerfile, 2.4/jessie/Dockerfile, 2.4/jessie/slim/Dockerfile, 2.4/stretch/Dockerfile, 2.4/stretch/slim/Dockerfile, 2.5/alpine3.8/Dockerfile, 2.5/alpine3.9/Dockerfile, 2.5/stretch/Dockerfile, 2.5/stretch/slim/Dockerfile, 2.6/alpine3.8/Dockerfile, 2.6/alpine3.9/Dockerfile, 2.6/stretch/Dockerfile, 2.6/stretch/slim/Dockerfile, update.sh
> There have been a number of CVEs for vulnerabilities in Rubygems announced today https://www.ruby-lang.org/en/news/2019/03/05/multiple-vulnerabilities-in-rubygems/.
From the discussion on #255, I have only updated RubyGems on versions of Ruby that we install an explicit version of RubyGems newer than is bundled with the Ruby release. What this means is that 2.6 still has RubyGems 3.0.1 because I am assuming that a bugfix release is incoming (given the following comment):
> In that case, you should be fine sticking with just the latest Ruby patch release. Anytime there is a CVE in RubyGems, the Ruby team issues a new bugfix release for Ruby with the patch for that issue. ￼:+1:
> \- https://github.com/docker-library/ruby/pull/255#issuecomment-451012334
:point_up:If this is not the case, …
=> Bump RubyGems version for CVE fixes

2.4/alpine3.10/Dockerfile, 2.4/alpine3.9/Dockerfile, 2.4/jessie/Dockerfile, 2.4/jessie/slim/Dockerfile, 2.4/stretch/Dockerfile, 2.4/stretch/slim/Dockerfile, 2.5/alpine3.10/Dockerfile, 2.5/alpine3.9/Dockerfile, 2.5/stretch/Dockerfile, 2.5/stretch/slim/Dockerfile, 2.6/alpine3.10/Dockerfile, 2.6/alpine3.9/Dockerfile, 2.6/stretch/Dockerfile, 2.6/stretch/slim/Dockerfile, 2.7-rc/alpine3.10/Dockerfile, 2.7-rc/buster/Dockerfile, 2.7-rc/buster/slim/Dockerfile, Dockerfile-alpine.template, Dockerfile-debian.template, Dockerfile-slim.template
This should help make sure programmatically that we avoid the fears in https://github.com/docker-library/ruby/pull/283#pullrequestreview-254299383 (#161 + #131). :+1:
=> Add some verification that we have no "distro ruby" packages

2.4/alpine3.10/Dockerfile, 2.4/alpine3.9/Dockerfile, 2.4/jessie/Dockerfile, 2.4/jessie/slim/Dockerfile, 2.4/stretch/Dockerfile, 2.4/stretch/slim/Dockerfile, 2.5/alpine3.10/Dockerfile, 2.5/alpine3.9/Dockerfile, 2.5/stretch/Dockerfile, 2.5/stretch/slim/Dockerfile, 2.6/alpine3.10/Dockerfile, 2.6/alpine3.9/Dockerfile, 2.6/stretch/Dockerfile, 2.6/stretch/slim/Dockerfile, 2.7-rc/alpine3.10/Dockerfile, 2.7-rc/buster/Dockerfile, 2.7-rc/buster/slim/Dockerfile, Dockerfile-alpine.template, Dockerfile-debian.template, Dockerfile-slim.template
Bundler has a special configuration to be used when you want to use the global rubygems path to install gems.
Using this option makes no difference currently with respect to `BUNDLE_PATH=$GEM_HOME` but in the future bundler will append the ruby scope to `$BUNDLE_PATH`. It actually does that already when the installation path is specified via configuration (`bundle config path /usr/local/bundle`) or via command line flag (`bundle install --path /usr/local/bundle`), but due to a bug it doesn't do it when specified via the environment (`BUNDLE_PATH=/usr/local/bundle`), like in the official docker images.
This means that in future versions of bundler (where the bug is fixed), `BUNDLE_PATH=$GEM_HOME` will actually install gems to `$GEM_HOME/ruby/2.7.0`, for example. Setting …
=> Prefer `BUNDLE_PATH__SYSTEM=true`

2.4/alpine3.10/Dockerfile, 2.4/alpine3.9/Dockerfile, 2.4/buster/Dockerfile, 2.4/buster/slim/Dockerfile, 2.4/stretch/Dockerfile, 2.4/stretch/slim/Dockerfile, 2.5/alpine3.10/Dockerfile, 2.5/alpine3.9/Dockerfile, 2.5/stretch/Dockerfile, 2.5/stretch/slim/Dockerfile, 2.6/alpine3.10/Dockerfile, 2.6/alpine3.9/Dockerfile, 2.6/stretch/Dockerfile, 2.6/stretch/slim/Dockerfile, 2.7-rc/alpine3.10/Dockerfile, 2.7-rc/buster/Dockerfile, 2.7-rc/buster/slim/Dockerfile, Dockerfile-alpine.template, Dockerfile-debian.template, Dockerfile-slim.template
This reverts commit e040029c82501556371e9d84a9db607dfb1bba51.
The change has created some problems with the `--deployment` flag. I'm working on fixing those issues, but they will take time to propagate, so I think it's better to revert my changes for the moment.
The problem is related to incompatibilities between `BUNDLE_PATH` and `BUNDLE_PATH__SYSTEM` that @tianon somehow suspected in https://github.com/docker-library/ruby/pull/285#issuecomment-506516000, but that my basic smoke tests failed to detect.
I'm really sorry for the trouble, specially knowing that propagating changes to the actual Docker images is tricky (PR here, PR to official images repo...) and we now have to go through the whole process again :pray:.
Fixes #288.
=> Revert "Prefer `BUNDLE_PATH__SYSTEM=true`"

2.4/alpine3.10/Dockerfile, 2.4/alpine3.11/Dockerfile, 2.4/buster/Dockerfile, 2.4/buster/slim/Dockerfile, 2.4/stretch/Dockerfile, 2.4/stretch/slim/Dockerfile, 2.5/alpine3.10/Dockerfile, 2.5/alpine3.11/Dockerfile, 2.5/buster/Dockerfile, 2.5/buster/slim/Dockerfile, 2.5/stretch/Dockerfile, 2.5/stretch/slim/Dockerfile, 2.6/alpine3.10/Dockerfile, 2.6/alpine3.11/Dockerfile, 2.6/buster/Dockerfile, 2.6/buster/slim/Dockerfile, 2.6/stretch/Dockerfile, 2.6/stretch/slim/Dockerfile, 2.7/alpine3.10/Dockerfile, 2.7/alpine3.11/Dockerfile, 2.7/buster/Dockerfile, 2.7/buster/slim/Dockerfile, Dockerfile-alpine.template, Dockerfile-debian.template, Dockerfile-slim.template
Newer bundler versions install gems to `$GEM_HOME/ruby/<ruby_version>`, instead of directly to `$GEM_HOME`.
So we need to add the proper paths to `GEM_PATH` and `PATH` so that gems
and their executables are properly found.
This is the proposal to fix https://github.com/bundler/bundler/issues/7494.
These changes are expected to be fully backwards compatible and should pass all the smoke tests to be added to https://github.com/docker-library/official-images:
* ruby-binstubs: https://github.com/docker-library/official-images/pull/7166 and maybe https://github.com/docker-library/official-images/pull/7208 or https://github.com/docker-library/official-images/pull/7229 as a followup.
* ruby-bundler extended to check for "deployment" setups: …
=> Stop setting `BUNDLE_PATH`

2.5/alpine3.11/Dockerfile, 2.5/alpine3.12/Dockerfile, 2.6/alpine3.11/Dockerfile, 2.6/alpine3.12/Dockerfile, 2.7/alpine3.11/Dockerfile, 2.7/alpine3.12/Dockerfile, Dockerfile-alpine.template, generate-stackbrew-library.sh, update.sh
Context: the patch utility has been [removed](https://gitlab.alpinelinux.org/alpine/aports/-/issues/11001) from BusyBox.
=> Add Alpine 3.12

2.5/alpine3.11/Dockerfile, 2.5/alpine3.12/Dockerfile, 2.5/buster/Dockerfile, 2.5/buster/slim/Dockerfile, 2.5/stretch/Dockerfile, 2.5/stretch/slim/Dockerfile, 2.6/alpine3.11/Dockerfile, 2.6/alpine3.12/Dockerfile, 2.6/buster/Dockerfile, 2.6/buster/slim/Dockerfile, 2.6/stretch/Dockerfile, 2.6/stretch/slim/Dockerfile, 2.7/alpine3.11/Dockerfile, 2.7/alpine3.12/Dockerfile, 2.7/buster/Dockerfile, 2.7/buster/slim/Dockerfile, Dockerfile-alpine.template, Dockerfile-debian.template, Dockerfile-slim.template
Ruby docker images officially provided by ruby-lang.org set `LANG` as `C.UTF-8` by default.
https://hub.docker.com/r/rubylang/ruby/
https://github.com/ruby/ruby-docker-images/blob/36c5d8b68eb91e34825500e50ca677f5574401f7/Dockerfile#L3
https://github.com/docker-library/ruby/issues/45#issuecomment-117298344
> I'd rather see something more official from either Ruby or Rails upstreams
> recommending a UTF-8 locale by default than just the anecdote that it's
> "more common" or "more convenient".
I think it's the one so we should set it by default.
=> Set LANG by default

3.0-rc/alpine3.12/Dockerfile, 3.0-rc/buster/Dockerfile, 3.0-rc/buster/slim/Dockerfile, update.sh
Copied the files over from 2.7 and changed the versions and sha to be:
```sh
ENV RUBY_MAJOR 3.0-rc
ENV RUBY_VERSION 3.0.0-preview1
ENV RUBY_DOWNLOAD_SHA256 aa7cce0c99f4ea2145fef9b78d74a44857754396790cd23bad75d759811e7a2a
```
Not sure what the change in `update.sh` is supposed to be, but I followed the pattern anyway. Fingers crossed it works :crossed_fingers: .
Official release announcement: 
* https://www.ruby-lang.org/en/news/2020/09/25/ruby-3-0-0-preview1-released/
Needs this change to pass tests:
* https://github.com/docker-library/official-images/pull/8789
=> Add ruby 3.0.0-preview1

3.0/alpine3.12/Dockerfile, 3.0/buster/Dockerfile, 3.0/buster/slim/Dockerfile
https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/
I've generated these files via the following command:
```
$ mv 3.0-rc 3.0
$ docker run --rm -v $PWD:/app -w /app ruby ./update.sh
```
=> Ruby 3.0.0 is released

generate-stackbrew-library.sh
Follow up https://github.com/docker-library/ruby/pull/332
<details>
<summary> $ ./generate-stackbrew-library.sh  </summary>
```
Maintainers: Tianon Gravi <admwiggin@gmail.com> (@tianon),
Joseph Ferguson <yosifkit@gmail.com> (@yosifkit)
GitRepo: https://github.com/docker-library/ruby.git
Tags: 3.0.0-buster, 3.0-buster, 3-buster, buster, 3.0.0, 3.0, 3, latest
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, mips64le, ppc64le, s390x
GitCommit: 921f2e68671461785e822aa437b68433278263b9
Directory: 3.0/buster
Tags: 3.0.0-slim-buster, 3.0-slim-buster, 3-slim-buster, slim-buster, 3.0.0-slim, 3.0-slim, 3-slim, slim
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, mips64le, ppc64le, s390x
GitCommit: 921f2e68671461785e822aa437b68433278263b9
Directory: 3.0/buster/slim
Tags: …
```
=> Update generate-stackbrew-library.sh for Ruby 3.0

2.6/alpine3.14/Dockerfile, Dockerfile.template
In some way, GitHub changed how they present the `.patch` file :confused:
=> Update patch file shasum

2.6/bullseye/Dockerfile, 2.6/slim-bullseye/Dockerfile, 2.7/bullseye/Dockerfile, 2.7/slim-bullseye/Dockerfile, 2.7/slim-buster/Dockerfile, 3.0/bullseye/Dockerfile, 3.0/slim-bullseye/Dockerfile, 3.0/slim-buster/Dockerfile, Dockerfile.template, versions.json, versions.sh
[bullseye is out](https://www.debian.org/News/2021/20210814), let's add it.
Closes #356
=> Add `bullseye` & `bullseye-slim` versions

3.1-rc/alpine3.13/Dockerfile, 3.1-rc/alpine3.14/Dockerfile, 3.1-rc/bullseye/Dockerfile, 3.1-rc/buster/Dockerfile, 3.1-rc/slim-bullseye/Dockerfile, 3.1-rc/slim-buster/Dockerfile, versions.json
Announcement: https://www.ruby-lang.org/en/news/2021/11/09/ruby-3-1-0-preview1-released/
Updated using the `update.sh` script. Is alpine 3.13 and debian buster images still supported or should only the latest be kept?
=> Add ruby 3.1.0-preview1

3.2/alpine3.16/Dockerfile, 3.2/alpine3.17/Dockerfile, 3.2/bullseye/Dockerfile, 3.2/buster/Dockerfile, 3.2/slim-bullseye/Dockerfile, 3.2/slim-buster/Dockerfile, Dockerfile.template, rust.json, rust.sh, versions.json, versions.sh
use latest rust
related https://github.com/docker-library/ruby/issues/390
=> Add YJIT support to debian 3.2+

3.0/alpine3.16/Dockerfile, 3.1/alpine3.17/Dockerfile, 3.1/alpine3.18/Dockerfile, 3.2/alpine3.17/Dockerfile, 3.2/alpine3.18/Dockerfile, 3.3-rc/alpine3.17/Dockerfile, 3.3-rc/alpine3.18/Dockerfile, 3.3-rc/slim-bullseye/Dockerfile, 3.3-rc/slim-buster/Dockerfile, Dockerfile.template
Also, remove now unnecessary comment.
See https://github.com/ruby/ruby/blob/v3_3_0_preview1/NEWS.md#extreadline-is-retired
Refs #419
=> Remove unnecessary readline headers in 3.3+

3.0/bullseye/Dockerfile, 3.0/buster/Dockerfile, 3.0/slim-bullseye/Dockerfile, 3.0/slim-buster/Dockerfile, 3.1/bookworm/Dockerfile, 3.1/bullseye/Dockerfile, 3.1/slim-bookworm/Dockerfile, 3.1/slim-bullseye/Dockerfile, 3.2/bookworm/Dockerfile, 3.2/bullseye/Dockerfile, 3.2/slim-bookworm/Dockerfile, 3.2/slim-bullseye/Dockerfile, 3.3-rc/bookworm/Dockerfile, 3.3-rc/bullseye/Dockerfile, 3.3-rc/slim-bookworm/Dockerfile, 3.3-rc/slim-bullseye/Dockerfile, Dockerfile.template, versions.json, versions.sh
bookworm distro for different Ruby versions + 2.7.8 support
=> Add debian:bookworm

.gitignore, 3.3-rc/alpine3.18/Dockerfile, 3.3-rc/alpine3.19/Dockerfile, 3.3-rc/bookworm/Dockerfile, 3.3-rc/bullseye/Dockerfile, 3.3-rc/slim-bookworm/Dockerfile, 3.3-rc/slim-bullseye/Dockerfile, Dockerfile.template, apply-templates.sh, generate-stackbrew-library.sh, versions.json, versions.sh
This ports our `versions.sh` script to finally actually parse https://github.com/ruby/www.ruby-lang.org/raw/master/_data/releases.yml directly instead of scraping the data from the webpages generated from it.
Additionally, this *should* allow us to automatically pick up GA releases after the pre-release (we can find out whether it worked next week!)
=> Finally parse upstream releases data properly

3.3/alpine3.18/Dockerfile, 3.3/alpine3.19/Dockerfile, 3.3/bookworm/Dockerfile, 3.3/bullseye/Dockerfile, 3.3/slim-bookworm/Dockerfile, 3.3/slim-bullseye/Dockerfile, Dockerfile.template
Ruby 3.3.0 has a bug which crashs many practical programs on linux-aarch64 (especially on Linux VMs on macOS, e.g. Docker Desktop).
https://bugs.ruby-lang.org/issues/20085
This bug is fixed in upstream and is planned to be backported, but no date is given yet for the 3.3.1 release.
https://github.com/ruby/ruby/pull/9371
This patch workarounds this bug by passing ASFLAGS to ./configure as described in https://bugs.ruby-lang.org/issues/20085#note-5 .
=> Workaround 3.3.0 crash on aarch64

3.3/alpine3.18/Dockerfile, 3.3/alpine3.19/Dockerfile, 3.3/bookworm/Dockerfile, 3.3/bullseye/Dockerfile, 3.3/slim-bookworm/Dockerfile, 3.3/slim-bullseye/Dockerfile, Dockerfile.template
Follow-up to https://github.com/docker-library/ruby/pull/439, see https://bugs.ruby-lang.org/issues/20085#note-30 :facepalm:
=> Apply arm64 patch sooner so `autoconf` regenerates `configure` correctly

3.0/alpine3.16/Dockerfile, 3.0/bullseye/Dockerfile, 3.0/buster/Dockerfile, 3.0/slim-bullseye/Dockerfile, 3.0/slim-buster/Dockerfile, 3.1/alpine3.18/Dockerfile, 3.1/alpine3.19/Dockerfile, 3.1/bookworm/Dockerfile, 3.1/bullseye/Dockerfile, 3.1/slim-bookworm/Dockerfile, 3.1/slim-bullseye/Dockerfile, 3.2/alpine3.18/Dockerfile, 3.2/alpine3.19/Dockerfile, 3.2/bookworm/Dockerfile, 3.2/bullseye/Dockerfile, 3.2/slim-bookworm/Dockerfile, 3.2/slim-bullseye/Dockerfile, 3.3/alpine3.18/Dockerfile, 3.3/alpine3.19/Dockerfile, 3.3/bookworm/Dockerfile, 3.3/bullseye/Dockerfile, 3.3/slim-bookworm/Dockerfile, 3.3/slim-bullseye/Dockerfile, versions.json
Normally I would let the bot handle this, but our build tests there have been slow so this should get the updates in faster.
https://www.ruby-lang.org/en/news/2024/04/23/ruby-3-3-1-released/
https://www.ruby-lang.org/en/news/2024/04/23/ruby-3-2-4-released/
https://www.ruby-lang.org/en/news/2024/04/23/ruby-3-1-5-released/
https://www.ruby-lang.org/en/news/2024/04/23/ruby-3-0-7-released/
https://www.ruby-lang.org/en/news/2024/04/23/arbitrary-memory-address-read-regexp-cve-2024-27282/
https://www.ruby-lang.org/en/news/2024/03/21/rce-rdoc-cve-2024-27281/
https://www.ruby-lang.org/en/news/2024/03/21/buffer-overread-cve-2024-27280/
=> [security] Update to 3.3.1, 3.2.4, 3.1.5, 3.0.7

3.0/alpine3.16/Dockerfile, 3.0/bullseye/Dockerfile, 3.0/buster/Dockerfile, 3.0/slim-bullseye/Dockerfile, 3.0/slim-buster/Dockerfile, Dockerfile.template
(since it's effectively EOL now except the possibility of a severe regression: https://www.ruby-lang.org/en/news/2024/04/23/ruby-3-0-7-released/)
See https://github.com/docker-library/ruby/pull/435
=> Revert RUBY_MAJOR refactoring for 3.0

Dockerfile.template
=> Remove 3.3.0 arm64 patch

.github/workflows/ci.yml, .github/workflows/verify-templating.yml
This clears these deprecation warnings ([example](https://github.com/docker-library/ruby/actions/runs/8835710682)):
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3.
> For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
=> Bump `actions/checkout` to v4

3.1/alpine3.19/Dockerfile, 3.1/alpine3.20/Dockerfile, 3.1/bookworm/Dockerfile, 3.1/bullseye/Dockerfile, 3.1/slim-bookworm/Dockerfile, 3.1/slim-bullseye/Dockerfile, 3.2/alpine3.19/Dockerfile, 3.2/alpine3.20/Dockerfile, 3.2/bookworm/Dockerfile, 3.2/bullseye/Dockerfile, 3.2/slim-bookworm/Dockerfile, 3.2/slim-bullseye/Dockerfile, 3.3/alpine3.19/Dockerfile, 3.3/alpine3.20/Dockerfile, 3.3/bookworm/Dockerfile, 3.3/bullseye/Dockerfile, 3.3/slim-bookworm/Dockerfile, 3.3/slim-bullseye/Dockerfile, 3.4-rc/alpine3.19/Dockerfile, 3.4-rc/alpine3.20/Dockerfile, 3.4-rc/bookworm/Dockerfile, 3.4-rc/bullseye/Dockerfile, 3.4-rc/slim-bookworm/Dockerfile, 3.4-rc/slim-bullseye/Dockerfile, Dockerfile.template
This drops the `-p` argument in `mkdir -p "$GEM_HOME"` to ensure that this validates our assumption that our `GEM_HOME` did _not_ exist before this line and is indeed created (as a new, empty directory) by this line.
cc @whalelines (whose idea validating better this was)
=> Add more defensive `mkdir` for `GEM_HOME`

3.2/alpine3.19/Dockerfile, 3.2/alpine3.20/Dockerfile, 3.2/bookworm/Dockerfile, 3.2/bullseye/Dockerfile, 3.2/slim-bookworm/Dockerfile, 3.2/slim-bullseye/Dockerfile, 3.3/alpine3.19/Dockerfile, 3.3/alpine3.20/Dockerfile, 3.3/bookworm/Dockerfile, 3.3/bullseye/Dockerfile, 3.3/slim-bookworm/Dockerfile, 3.3/slim-bullseye/Dockerfile, 3.4-rc/alpine3.19/Dockerfile, 3.4-rc/alpine3.20/Dockerfile, 3.4-rc/bookworm/Dockerfile, 3.4-rc/bullseye/Dockerfile, 3.4-rc/slim-bookworm/Dockerfile, 3.4-rc/slim-bullseye/Dockerfile, rust.json, versions.json
The last bump was in https://github.com/docker-library/ruby/commit/423e364cd1681dac6b5afd6191d774aaa1cf6161, about 11 months ago.
I have no particular reason for this change except that I feel an update should happen at some point. Every rust version would be excessive but updating it every 6-12 months (or some other cadence) feels appropriate. Could be automated.
=> Bump rust version

3.2/alpine3.19/Dockerfile, 3.2/alpine3.20/Dockerfile, 3.2/bookworm/Dockerfile, 3.2/bullseye/Dockerfile, 3.2/slim-bookworm/Dockerfile, 3.2/slim-bullseye/Dockerfile, 3.3/alpine3.19/Dockerfile, 3.3/alpine3.20/Dockerfile, 3.3/bookworm/Dockerfile, 3.3/bullseye/Dockerfile, 3.3/slim-bookworm/Dockerfile, 3.3/slim-bullseye/Dockerfile, 3.4-rc/alpine3.19/Dockerfile, 3.4-rc/alpine3.20/Dockerfile, 3.4-rc/bookworm/Dockerfile, 3.4-rc/bullseye/Dockerfile, 3.4-rc/slim-bookworm/Dockerfile, 3.4-rc/slim-bullseye/Dockerfile, rust.json, versions.json
This reverts commit 89946d97bef298806314fc65a21f116fe5b7165b, reversing changes made to 7cb059ddbec27b57a9430d4369bde018b9de06b7.
I chose an inopportune time to do this.
There is an upstream issue where builds on arm64/v8 fail: https://bugs.ruby-lang.org/issues/20506
Example failure: https://doi-janky.infosiftr.net/job/wip/job/new/job/build-arm64v8/45573/console
I believe https://github.com/rust-lang/rust/pull/131221 will fix this but it is only slated for Rust 1.83
=> Revert "Bump rust version" 

3.1/alpine3.19/Dockerfile, 3.1/alpine3.20/Dockerfile, 3.2/alpine3.19/Dockerfile, 3.2/alpine3.20/Dockerfile, 3.3/alpine3.19/Dockerfile, 3.3/alpine3.20/Dockerfile, 3.4-rc/alpine3.19/Dockerfile, 3.4-rc/alpine3.20/Dockerfile, Dockerfile.template
I believe this was fixed with https://github.com/ruby/ruby/commit/74f94b3e6ebf15b76f3b357e754095412b006e94
https://bugs.ruby-lang.org/issues/15595
This was shipped with Ruby 2.7, so it should be unnecessary now. I'll check the build output if that is indeed the case.
=> Remove alpine isnan/isinf workaround

3.1/alpine3.20/Dockerfile, 3.1/alpine3.21/Dockerfile, 3.1/bookworm/Dockerfile, 3.1/bullseye/Dockerfile, 3.1/slim-bookworm/Dockerfile, 3.1/slim-bullseye/Dockerfile, 3.2/alpine3.20/Dockerfile, 3.2/alpine3.21/Dockerfile, 3.2/bookworm/Dockerfile, 3.2/bullseye/Dockerfile, 3.2/slim-bookworm/Dockerfile, 3.2/slim-bullseye/Dockerfile, 3.3/alpine3.20/Dockerfile, 3.3/alpine3.21/Dockerfile, 3.3/bookworm/Dockerfile, 3.3/bullseye/Dockerfile, 3.3/slim-bookworm/Dockerfile, 3.3/slim-bullseye/Dockerfile, 3.4-rc/alpine3.20/Dockerfile, 3.4-rc/alpine3.21/Dockerfile, 3.4-rc/bookworm/Dockerfile, 3.4-rc/bullseye/Dockerfile, 3.4-rc/slim-bookworm/Dockerfile, 3.4-rc/slim-bullseye/Dockerfile, Dockerfile.template
Per https://stackoverflow.com/questions/1381725/how-to-make-no-ri-no-rdoc-the-default-for-gem-install#comment22636260_7662245 this is possible since rubygems 2.0.0 from 2012.
I updated the comment to indicate this is only for the `gem` command, bundler already doesn't do this by default.
It works (no `Parsing documentation...`):
```
$ gem install rubocop -v 1.69.0
Fetching rubocop-1.69.0.gem
Successfully installed rubocop-1.69.0
1 gem installed
$ gem update rubocop
Updating installed gems
Updating rubocop
Fetching rubocop-1.69.1.gem
Successfully installed rubocop-1.69.1
Gems updated: rubocop
```
=> Simplify gemrc nodoc

3.2/alpine3.20/Dockerfile, 3.2/alpine3.21/Dockerfile, 3.2/bookworm/Dockerfile, 3.2/bullseye/Dockerfile, 3.2/slim-bookworm/Dockerfile, 3.2/slim-bullseye/Dockerfile, 3.3/alpine3.20/Dockerfile, 3.3/alpine3.21/Dockerfile, 3.3/bookworm/Dockerfile, 3.3/bullseye/Dockerfile, 3.3/slim-bookworm/Dockerfile, 3.3/slim-bullseye/Dockerfile, 3.4/alpine3.20/Dockerfile, 3.4/alpine3.21/Dockerfile, 3.4/bookworm/Dockerfile, 3.4/bullseye/Dockerfile, 3.4/slim-bookworm/Dockerfile, 3.4/slim-bullseye/Dockerfile, rust.json, versions.json
This is a redo of https://github.com/docker-library/ruby/pull/478, now that there are no compilation issues for some platforms anymore. The previous bump to 1.82 failed to compile on some alpine platforms.
See https://bugs.ruby-lang.org/issues/20506 and https://github.com/docker-library/ruby/pull/479
Here's a build with all the variants showing that it works fine: https://github.com/docker-ruby-nightly/ruby/actions/runs/12745941206
=> Bump Rust to 1.84.0

3.1/alpine3.20/Dockerfile, 3.1/alpine3.21/Dockerfile, 3.1/slim-bookworm/Dockerfile, 3.1/slim-bullseye/Dockerfile, 3.2/alpine3.20/Dockerfile, 3.2/alpine3.21/Dockerfile, 3.2/slim-bookworm/Dockerfile, 3.2/slim-bullseye/Dockerfile, 3.3/alpine3.20/Dockerfile, 3.3/alpine3.21/Dockerfile, 3.3/slim-bookworm/Dockerfile, 3.3/slim-bullseye/Dockerfile, 3.4/alpine3.20/Dockerfile, 3.4/alpine3.21/Dockerfile, 3.4/slim-bookworm/Dockerfile, 3.4/slim-bullseye/Dockerfile, Dockerfile.template
These were never intended to be part of the "interface" of the `slim` and `alpine` images -- they were included before we had fancy `ldd`/`scanelf`-based runtime dependency inclusion, and were a metapackage that helped us avoid the complexity of `libyaml3` vs `libyaml4` (and making sure we install the correct one).  This moves them to explicit build-time dependencies accordingly, as they should've always been.
Closes https://github.com/docker-library/ruby/issues/492
Refs:
- https://github.com/docker-library/ruby/pull/349
- https://github.com/docker-library/ruby/pull/60
- https://github.com/docker-library/ruby/pull/33
- https://github.com/docker-library/ruby/issues/492#issuecomment-2576425196
=> Remove runtime dependencies from slim and alpine variants

3.1/alpine3.20/Dockerfile, 3.1/alpine3.21/Dockerfile, 3.1/bookworm/Dockerfile, 3.1/bullseye/Dockerfile, 3.1/slim-bookworm/Dockerfile, 3.1/slim-bullseye/Dockerfile, 3.2/alpine3.20/Dockerfile, 3.2/alpine3.21/Dockerfile, 3.2/bookworm/Dockerfile, 3.2/bullseye/Dockerfile, 3.2/slim-bookworm/Dockerfile, 3.2/slim-bullseye/Dockerfile, 3.3/alpine3.20/Dockerfile, 3.3/alpine3.21/Dockerfile, 3.3/bookworm/Dockerfile, 3.3/bullseye/Dockerfile, 3.3/slim-bookworm/Dockerfile, 3.3/slim-bullseye/Dockerfile, 3.4/alpine3.20/Dockerfile, 3.4/alpine3.21/Dockerfile, 3.4/bookworm/Dockerfile, 3.4/bullseye/Dockerfile, 3.4/slim-bookworm/Dockerfile, 3.4/slim-bullseye/Dockerfile, Dockerfile.template
This reverts commit 7f078b1b01338e19130eb8b01cb7f35153ba6b04. (https://github.com/docker-library/ruby/pull/493)
It looks like this change is too disruptive. For example, modern rails apps all transitively depend in `psych` which requires libyaml. Coincidentally my own builds would fail with this.
I still think this change makes sense, but should probably only be part of the next Ruby version so it doesn't suddently break for lots of people.
Closes #495, closes #496
=> Revert "Remove runtime dependencies from slim and alpine variants"

3.1/alpine3.20/Dockerfile, 3.1/alpine3.21/Dockerfile, 3.1/bookworm/Dockerfile, 3.1/bullseye/Dockerfile, 3.1/slim-bookworm/Dockerfile, 3.1/slim-bullseye/Dockerfile, 3.2/alpine3.20/Dockerfile, 3.2/alpine3.21/Dockerfile, 3.2/bookworm/Dockerfile, 3.2/bullseye/Dockerfile, 3.2/slim-bookworm/Dockerfile, 3.2/slim-bullseye/Dockerfile, 3.3/alpine3.20/Dockerfile, 3.3/alpine3.21/Dockerfile, 3.3/bookworm/Dockerfile, 3.3/bullseye/Dockerfile, 3.3/slim-bookworm/Dockerfile, 3.3/slim-bullseye/Dockerfile, 3.4/alpine3.20/Dockerfile, 3.4/alpine3.21/Dockerfile, 3.4/bookworm/Dockerfile, 3.4/bullseye/Dockerfile, 3.4/slim-bookworm/Dockerfile, 3.4/slim-bullseye/Dockerfile, Dockerfile.template
Since Ruby 2.7, this warning is not emitted anymore It was removed as part of https://bugs.ruby-lang.org/issues/16131
Here's the output of running `ENV['PATH']` against various ruby versions, when `$PATH` contains a world-writable folder:
```
===============1.8.7-p374================
-e:1: warning: Insecure world writable dir /app/whatever in PATH, mode 040757
===============1.9.3-p551================
-e:1: warning: Insecure world writable dir /app/whatever in PATH, mode 040757
===============2.0.0-p648================
-e:1: warning: Insecure world writable dir /app/whatever in PATH, mode 040757
=================2.1.10==================
-e:1: warning: Insecure world writable dir /app/whatever in PATH, mode 040757
=================2.2.10==================
-e:1: warning: Insecure world …
```
=> Remove `ENABLE_PATH_CHECK` workaround

Dockerfile.template
None of these specific versions are build anymroe
=> Remove slim/alpine temporary code

Dockerfile.template
All versions are build with rust, so it is always present
=> Remove `.rust.version` check

3.2/bookworm/Dockerfile, 3.2/slim-bookworm/Dockerfile, 3.2/slim-trixie/Dockerfile, 3.2/trixie/Dockerfile, 3.3/bookworm/Dockerfile, 3.3/slim-bookworm/Dockerfile, 3.3/slim-trixie/Dockerfile, 3.3/trixie/Dockerfile, 3.4/bookworm/Dockerfile, 3.4/slim-bookworm/Dockerfile, 3.4/slim-trixie/Dockerfile, 3.4/trixie/Dockerfile, 3.5-rc/bookworm/Dockerfile, 3.5-rc/slim-bookworm/Dockerfile, 3.5-rc/slim-trixie/Dockerfile, 3.5-rc/trixie/Dockerfile, Dockerfile.template, versions.json, versions.sh
Same as https://github.com/docker-library/ruby/pull/514 but fixed for ruby 3.2. Took some stuff from https://github.com/docker-library/python/pull/1042 as well.
For Ruby 3.2 `libreadline-dev` is being installed which causes unwanted output during `dpkg-query --search`:
```sh
dpkg-query --search *lib/x86_64-linux-gnu/libreadline.so.8
diversion by libreadline8t64 from: /lib/x86_64-linux-gnu/libreadline.so.8
diversion by libreadline8t64 to: /lib/x86_64-linux-gnu/libreadline.so.8.usr-is-merged
diversion by libreadline8t64 from: /lib/x86_64-linux-gnu/libreadline.so.8.2
diversion by libreadline8t64 to: /lib/x86_64-linux-gnu/libreadline.so.8.2.usr-is-merged
libreadline8t64:amd64: /usr/lib/x86_64-linux-gnu/libreadline.so.8.2
libreadline8t64:amd64: /usr/lib/x86_64-linux-gnu/libreadline.so.8 …
```
=> Add debian trixie/Drop debian bullseye
