1.9/slim/Dockerfile
2.0/slim/Dockerfile
2.1/slim/Dockerfile
2.2/slim/Dockerfile
generate-stackbrew-library.sh
update.sh

Sizes and tests coming monday.
Fixes #30

Slim for all the versions

---

2.0/Dockerfile
2.1/Dockerfile
2.2/Dockerfile
update.sh

Fixes #36
For real this time - I promise.

Fix update script and add sha256 validation

---

2.0/Dockerfile
2.0/onbuild/Dockerfile
2.0/slim/Dockerfile
2.0/wheezy/Dockerfile
2.1/Dockerfile
2.1/onbuild/Dockerfile
2.1/slim/Dockerfile
2.1/wheezy/Dockerfile
2.2/Dockerfile
2.2/onbuild/Dockerfile
2.2/slim/Dockerfile
2.2/wheezy/Dockerfile

2.2.2
2.1.6
2.0.0-p645
Signed-off-by: Brian Goff <cpuguy83@gmail.com>

Bump ruby minor versions

---

2.0/Dockerfile
2.0/slim/Dockerfile
2.0/wheezy/Dockerfile
2.1/Dockerfile
2.1/slim/Dockerfile
2.1/wheezy/Dockerfile
2.2/Dockerfile
2.2/slim/Dockerfile
2.2/wheezy/Dockerfile
update.sh

In the same spirit as https://github.com/docker-library/python/pull/46 and https://github.com/docker-library/node/pull/17.

Add an explicit BUNDLER_VERSION

---

2.0/Dockerfile
2.0/slim/Dockerfile
2.1/Dockerfile
2.1/slim/Dockerfile
2.2/Dockerfile
2.2/slim/Dockerfile

It is synonymous with `--no-rdoc --no-ri`, but newer, and slightly more obvious.
Discussed in #48.

Use --no-document flag in .gemrc

---

2.1/alpine/Dockerfile
2.2/alpine/Dockerfile
2.3/alpine/Dockerfile
Dockerfile-alpine.template

Fixes #75
(Included a comment so that we can have _some_ way to test whether this change might be revertible in the future.)

Switch libedit for readline to fix irb segfaults

---

2.1/alpine/Dockerfile
2.2/alpine/Dockerfile
2.3/alpine/Dockerfile
Dockerfile-alpine.template

[alpine:3.4](https://github.com/gliderlabs/docker-alpine/pull/179) is finally out with some [important fixes](http://alpinelinux.org/posts/Alpine-3.4.0-released.html) (mainly the DNS fix that makes Alpine compatible with Kubernetes).

Update alpine to 3.4

---

2.1/Dockerfile
2.1/alpine/Dockerfile
2.1/slim/Dockerfile
2.2/Dockerfile
2.2/alpine/Dockerfile
2.2/slim/Dockerfile
2.3/Dockerfile
2.3/alpine/Dockerfile
2.3/slim/Dockerfile
Dockerfile-alpine.template
Dockerfile-slim.template
Dockerfile.template
update.sh

Switched to https when fetching Ruby

---

.travis.yml
2.4/Dockerfile
2.4/alpine/Dockerfile
2.4/onbuild/Dockerfile
2.4/slim/Dockerfile

Update to 2.4.0 release.

---

2.1/alpine/Dockerfile
2.2/alpine/Dockerfile
2.3/alpine/Dockerfile
2.4/alpine/Dockerfile
Dockerfile-alpine.template

Reverts docker-library/ruby#103
See https://github.com/docker-library/golang/pull/131#issuecomment-270677556 for further discussion.
Closes #104
Closes #106

Revert "Update to Alpine 3.5"

---

2.1/Dockerfile
2.2/Dockerfile
2.3/Dockerfile
2.4/Dockerfile
Dockerfile.template

Stop removing "xz-utils" in non-slim base (inhertied from "buildpack-deps:jessie")

---

.travis.yml
2.4/alpine3.6/Dockerfile

Add "alpine3.6" variant of 2.4

---

2.2/alpine3.4/Dockerfile
2.3/alpine3.4/Dockerfile
2.4/alpine3.4/Dockerfile
2.4/alpine3.6/Dockerfile
Dockerfile-alpine.template
update.sh

Switch from "openssl" to "libressl" for Alpine 3.6+

---

2.2/alpine3.4/Dockerfile
2.2/jessie/Dockerfile
2.2/jessie/slim/Dockerfile
2.3/alpine3.4/Dockerfile
2.3/jessie/Dockerfile
2.3/jessie/slim/Dockerfile
2.4/alpine3.4/Dockerfile
2.4/alpine3.6/Dockerfile
2.4/alpine3.7/Dockerfile
2.4/jessie/Dockerfile
2.4/jessie/slim/Dockerfile
2.4/stretch/Dockerfile
2.4/stretch/slim/Dockerfile
2.5/alpine3.7/Dockerfile
2.5/stretch/Dockerfile
2.5/stretch/slim/Dockerfile
Dockerfile-alpine.template
Dockerfile-debian.template
Dockerfile-slim.template

Remove /root/.gem to shrink image size

---

.travis.yml
2.3/stretch/Dockerfile
2.3/stretch/slim/Dockerfile
Dockerfile-debian.template
update.sh

I have built and the images appear to work OK

Add stretch variants of 2.3

---

2.3/alpine3.7/Dockerfile
2.4/alpine3.6/Dockerfile
2.4/alpine3.7/Dockerfile
2.5/alpine3.7/Dockerfile
2.6-rc/alpine3.7/Dockerfile
Dockerfile-alpine.template

Closes #229
See discussion over on #229, especially https://github.com/alpinelinux/aports/commit/d9815d1f515a00113cd2fc786b9f50a52bff8400. :+1:

Add "--no-network" to all APK invocations that shouldn't need to hit the mirrors for any reason

---

.travis.yml
2.6/alpine3.7/Dockerfile
2.6/alpine3.8/Dockerfile
2.6/stretch/Dockerfile
2.6/stretch/slim/Dockerfile
generate-stackbrew-library.sh

Upgrade 2.6

---

.travis.yml
2.3/alpine3.7/Dockerfile
2.3/alpine3.8/Dockerfile
2.4/alpine3.8/Dockerfile
2.4/alpine3.9/Dockerfile
2.5/alpine3.8/Dockerfile
2.5/alpine3.9/Dockerfile
2.6/alpine3.8/Dockerfile
2.6/alpine3.9/Dockerfile
Dockerfile-alpine.template
generate-stackbrew-library.sh
update.sh

Update to Alpine 3.9 (dropping Alpine 3.7)

---

2.7-rc/alpine3.10/Dockerfile
2.7-rc/buster/Dockerfile
2.7-rc/buster/slim/Dockerfile
update.sh

Released on 22 Oct 2019: https://www.ruby-lang.org/en/news/2019/10/22/ruby-2-7-0-preview2-released/
This is an initial attempt and might not work (or need some cleanup).

Update 2.7 to preview2 version

---

2.6/alpine3.15/Dockerfile
2.7/alpine3.15/Dockerfile
3.0/alpine3.15/Dockerfile
3.1-rc/alpine3.15/Dockerfile
versions.json
versions.sh

Update to Alpine 3.15

---

3.2-rc/alpine3.14/Dockerfile
3.2-rc/alpine3.15/Dockerfile
3.2-rc/bullseye/Dockerfile
3.2-rc/buster/Dockerfile
3.2-rc/slim-bullseye/Dockerfile
3.2-rc/slim-buster/Dockerfile
versions.json

https://www.ruby-lang.org/en/news/2022/04/03/ruby-3-2-0-preview1-released/

Add 3.2.0-preview1

---

2.6/alpine3.14/Dockerfile
2.6/alpine3.15/Dockerfile
2.6/bullseye/Dockerfile
2.6/buster/Dockerfile
2.6/slim-bullseye/Dockerfile
2.6/slim-buster/Dockerfile
2.7/alpine3.14/Dockerfile
2.7/alpine3.15/Dockerfile
2.7/bullseye/Dockerfile
2.7/buster/Dockerfile
2.7/slim-bullseye/Dockerfile
2.7/slim-buster/Dockerfile
3.0/alpine3.14/Dockerfile
3.0/alpine3.15/Dockerfile
3.0/bullseye/Dockerfile
3.0/buster/Dockerfile
3.0/slim-bullseye/Dockerfile
3.0/slim-buster/Dockerfile
3.1/alpine3.14/Dockerfile
3.1/alpine3.15/Dockerfile
3.1/bullseye/Dockerfile
3.1/buster/Dockerfile
3.1/slim-bullseye/Dockerfile
3.1/slim-buster/Dockerfile
versions.json

https://www.ruby-lang.org/en/news/2022/04/12/ruby-2-6-10-released/
https://www.ruby-lang.org/en/news/2022/04/12/ruby-2-7-6-released/
https://www.ruby-lang.org/en/news/2022/04/12/ruby-3-0-4-released/
https://www.ruby-lang.org/en/news/2022/04/12/ruby-3-1-2-released/

ruby-{2.6.10,2.7.6,3.0.4,3.1.2} 

---

3.2-rc/alpine3.16/Dockerfile
Dockerfile.template

(specifically, Rust 1.58.1+, currently only Alpine)
Closes #390
@seandilda :bow:

Add YJIT support to 3.2+ where we have new enough Rust

---

3.2/alpine3.16/Dockerfile
3.2/alpine3.17/Dockerfile
3.2/bullseye/Dockerfile
3.2/buster/Dockerfile
3.2/slim-bullseye/Dockerfile
3.2/slim-buster/Dockerfile
versions.json

https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/

Update 3.2.0-rc to 3.2.0

---

3.2/alpine3.16/Dockerfile
3.2/alpine3.17/Dockerfile
3.2/bullseye/Dockerfile
3.2/buster/Dockerfile
3.2/slim-bullseye/Dockerfile
3.2/slim-buster/Dockerfile
versions.json

https://www.ruby-lang.org/en/news/2023/02/08/ruby-3-2-1-released/

Update 3.2.0 to 3.2.1

---

2.7/alpine3.16/Dockerfile
2.7/bullseye/Dockerfile
2.7/buster/Dockerfile
2.7/slim-bullseye/Dockerfile
2.7/slim-buster/Dockerfile
3.0/alpine3.16/Dockerfile
3.0/bullseye/Dockerfile
3.0/buster/Dockerfile
3.0/slim-bullseye/Dockerfile
3.0/slim-buster/Dockerfile
3.1/alpine3.16/Dockerfile
3.1/alpine3.17/Dockerfile
3.1/bullseye/Dockerfile
3.1/buster/Dockerfile
3.1/slim-bullseye/Dockerfile
3.1/slim-buster/Dockerfile
3.2/alpine3.16/Dockerfile
3.2/alpine3.17/Dockerfile
3.2/bullseye/Dockerfile
3.2/buster/Dockerfile
3.2/slim-bullseye/Dockerfile
3.2/slim-buster/Dockerfile
Dockerfile.template

This still supports the "arbitrary user" use case but with slightly tighter permissions on the end result.

Update permissions from 777 to 1777

---

3.1/alpine3.19/Dockerfile
3.2/alpine3.18/Dockerfile
3.2/alpine3.19/Dockerfile
3.2/bookworm/Dockerfile
3.2/bullseye/Dockerfile
3.2/slim-bookworm/Dockerfile
3.2/slim-bullseye/Dockerfile
3.3-rc/alpine3.18/Dockerfile
3.3-rc/alpine3.19/Dockerfile
3.3-rc/bookworm/Dockerfile
3.3-rc/bullseye/Dockerfile
3.3-rc/slim-bookworm/Dockerfile
3.3-rc/slim-bullseye/Dockerfile
rust.json
versions.json
versions.sh

https://www.alpinelinux.org/posts/Alpine-3.19.0-released.html
It's that time again.

Add alpine 3.19

---

3.0/bullseye/Dockerfile
3.0/buster/Dockerfile
3.0/slim-bullseye/Dockerfile
3.0/slim-buster/Dockerfile
3.1/bookworm/Dockerfile
3.1/bullseye/Dockerfile
3.1/slim-bookworm/Dockerfile
3.1/slim-bullseye/Dockerfile
3.2/bookworm/Dockerfile
3.2/bullseye/Dockerfile
3.2/slim-bookworm/Dockerfile
3.2/slim-bullseye/Dockerfile
3.3/bookworm/Dockerfile
3.3/bullseye/Dockerfile
3.3/slim-bookworm/Dockerfile
3.3/slim-bullseye/Dockerfile
Dockerfile.template

Fix `dpkg-query --search` to be more specific

---

3.4-rc/alpine3.18/Dockerfile
3.4-rc/alpine3.19/Dockerfile
3.4-rc/bookworm/Dockerfile
3.4-rc/bullseye/Dockerfile
3.4-rc/slim-bookworm/Dockerfile
3.4-rc/slim-bullseye/Dockerfile
versions.json

Add 3.4-rc

---

3.1/alpine3.20/Dockerfile
3.2/alpine3.20/Dockerfile
3.3/alpine3.20/Dockerfile
3.4-rc/alpine3.20/Dockerfile
versions.json
versions.sh

https://alpinelinux.org/posts/Alpine-3.20.0-released.html
Looks like it already have been 6 months since the last one.

Add alpine 3.20

---

3.1/alpine3.21/Dockerfile
3.2/alpine3.21/Dockerfile
3.3/alpine3.21/Dockerfile
3.4-rc/alpine3.21/Dockerfile
versions.json
versions.sh

https://alpinelinux.org/posts/Alpine-3.21.0-released.html
As customary, drop alpine 3.19

Add alpine 3.21

---

3.5-rc/alpine3.20/Dockerfile
3.5-rc/alpine3.21/Dockerfile
3.5-rc/bookworm/Dockerfile
3.5-rc/bullseye/Dockerfile
3.5-rc/slim-bookworm/Dockerfile
3.5-rc/slim-bullseye/Dockerfile
versions.json

See https://www.ruby-lang.org/en/news/2025/04/18/ruby-3-5-0-preview1-released/

Add 3.5 pre-release
